### ISSUE TITLE
一个小小提议

### ISSUE THREAD

**Issue by RuCu6** [yjqiang/surge_scripts#10]
佬，可以去掉哔哩哔哩这个未成年弹窗吗
![34772235-235A-4D04-89DF-ED2F3C18D88D](https://user-images.githubusercontent.com/49463634/164583187-c1e61e52-0977-44ef-a2ff-a9bc08f80b76.png)

**Comment by yjqiang** [comment]
感觉这个东西是写死的，可能不是连接服务器通信后再展示的

**Comment by RuCu6** [comment]
好的 回复好迅速 感谢回复 感谢回复😝😝
