### ISSUE TITLE
微博出现广告了

### ISSUE THREAD

**Issue by xieft** [yjqiang/surge_scripts#4]
![IMG_4853](https://user-images.githubusercontent.com/35829258/136425058-36655b92-e2a9-49ec-8e70-cc63672aebc5.PNG)

**Comment by xieft** [comment]
发现页面的广告
![IMG_4855](https://user-images.githubusercontent.com/35829258/136491525-e407c968-0664-46b5-9fee-00afb9642f25.jpg)

**Comment by xieft** [comment]
> > 还有部分微博评论世界的推荐微博
> > ![IMG_4854](https://user-images.githubusercontent.com/35829258/136431061-a62fa02a-3147-4f4a-812e-2cbe901bd0a4.PNG)
> 
> 我觉得不太喜欢，应该不会考虑的



> > 还有某些微博评论下方的推荐微博
> > ![IMG_4854](https://user-images.githubusercontent.com/35829258/136431061-a62fa02a-3147-4f4a-812e-2cbe901bd0a4.PNG)
> 
> 这个我觉得无所谓，应该不会考虑屏蔽的

微博这种和自己毫无关系，内容耸动的内容强推送，个人认为非常影响使用体验

**Comment by yjqiang** [comment]
f27c72bd96fa28a1547c43451c960a5685479181 发现页的卡片广告，但是去的不完全，因为有的广告和正常的卡片，它们的数据格式没有区别

**Comment by yjqiang** [comment]
暂不考虑去除微博评论的推荐部分
