### ISSUE TITLE
知乎app更新后首页去广告功能已失效

### ISSUE THREAD

**Issue by yfue** [yjqiang/surge_scripts#6]
感谢大佬的工作🙏知乎app更新后首页去广告功能已失效

**Comment by yjqiang** [comment]
![9F6CA49A-FA34-4D78-8D25-DB6BBA80774E](https://user-images.githubusercontent.com/8900942/146292334-088efdd8-4652-4e7f-a90a-9d6a3ed7b628.png)
https://blankwonder.medium.com/surge-中文白皮书-草稿第三部分-转发-代理和规则系统-37c6319dc36
“ REJECT-DROP：拒绝该请求，与 REJECT 不同的是，该策略将静默抛弃请求。因为部分程序有着十分暴力的重试逻辑，连接失败后会立刻进行重试，导致请求风暴”
后面的 resolve 请求由于 surge 的策略，没有拦截，导致没法用了。目前还在想解决办法

**Comment by yjqiang** [comment]
可以 REJECT-NO-DROP 绕过
但发现还是不行，可能又有奇怪的东西mmp

**Comment by yjqiang** [comment]
85fa6b1c663e0fe1ea1f663d96131aec683f9f16
