### ISSUE TITLE
港区 bilibili 广告问题

### ISSUE THREAD

**Issue by IvorkChan** [yjqiang/surge_scripts#7]
最近港区上架了一个没有广告版本的 bilibili，使用脚本后在“我的”界面反而会多出创作中心……关闭脚本后就消失了，离谱。

**Comment by yjqiang** [comment]
https://github.com/yjqiang/surge_scripts/blob/main/dev/bilibili/bilibili_mine.js#L50

**Comment by yjqiang** [comment]
非常抱歉，最近事情比较多，之后我看看，删除广告之类的操作改为 filter，目前是用替换的方法实现的“删除”

**Comment by IvorkChan** [comment]
感谢回复！
之前担心打扰就把issue关闭了。
另，微博启动广告脚本同样失效，如果有时间，烦请查看。
